name: sm5
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  url_launcher: ^6.0.9
  logger: ^2.4.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/thumbnail.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/sm5_logo.png"
